// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmhBE1dP96TgTzOwJNV2TrndA4JGOqPYc',
    appId: '1:680308237166:web:1989de29541b427f5d177f',
    messagingSenderId: '680308237166',
    projectId: 'fluttercli-db114',
    authDomain: 'fluttercli-db114.firebaseapp.com',
    storageBucket: 'fluttercli-db114.appspot.com',
    measurementId: 'G-27J6DV8JFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqXJOSNAjTwaqHJd93lS101f-MJXD7VgA',
    appId: '1:680308237166:android:a88b7d8e970553595d177f',
    messagingSenderId: '680308237166',
    projectId: 'fluttercli-db114',
    storageBucket: 'fluttercli-db114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwqrrV4if2AgV6hez30jz2vngeQRhUM3Y',
    appId: '1:680308237166:ios:2cabeb1d8c9510b75d177f',
    messagingSenderId: '680308237166',
    projectId: 'fluttercli-db114',
    storageBucket: 'fluttercli-db114.appspot.com',
    iosBundleId: 'com.example.firebaseCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwqrrV4if2AgV6hez30jz2vngeQRhUM3Y',
    appId: '1:680308237166:ios:2cabeb1d8c9510b75d177f',
    messagingSenderId: '680308237166',
    projectId: 'fluttercli-db114',
    storageBucket: 'fluttercli-db114.appspot.com',
    iosBundleId: 'com.example.firebaseCli',
  );
}
